[env]
MACOSX_DEPLOYMENT_TARGET = "10.15"

[build]
rustflags = ["-C", "target-feature=+crt-static"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-mmacosx-version-min=10.15"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-mmacosx-version-min=10.15"]

[unstable]
build-std = ["core", "alloc"]
